/**
 * Vio-V
 * Vio-V API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CharacterBankLog {
    'CharacterID'?: number;
    'Timestamp'?: number;
    'Amount'?: string;
    'Reason'?: string;
    'Info'?: string;
    'Info1'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "CharacterID",
            "baseName": "CharacterID",
            "type": "number"
        },
        {
            "name": "Timestamp",
            "baseName": "Timestamp",
            "type": "number"
        },
        {
            "name": "Amount",
            "baseName": "Amount",
            "type": "string"
        },
        {
            "name": "Reason",
            "baseName": "Reason",
            "type": "string"
        },
        {
            "name": "Info",
            "baseName": "Info",
            "type": "string"
        },
        {
            "name": "Info1",
            "baseName": "Info1",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CharacterBankLog.attributeTypeMap;
    }
}

