/**
 * Vio-V
 * Vio-V API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GangArea {
    'ID': number;
    'DistriktID': number;
    'Name': string;
    'X': number;
    'Y': number;
    'Z': number;
    'Range': number;
    'Rotation': number;
    'Owner': number;
    'LastAttack': number;
    'ItemID': number;
    'Amount': number;
    'Impact': number;
    'OldOwner': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ID",
            "baseName": "ID",
            "type": "number"
        },
        {
            "name": "DistriktID",
            "baseName": "DistriktID",
            "type": "number"
        },
        {
            "name": "Name",
            "baseName": "Name",
            "type": "string"
        },
        {
            "name": "X",
            "baseName": "X",
            "type": "number"
        },
        {
            "name": "Y",
            "baseName": "Y",
            "type": "number"
        },
        {
            "name": "Z",
            "baseName": "Z",
            "type": "number"
        },
        {
            "name": "Range",
            "baseName": "Range",
            "type": "number"
        },
        {
            "name": "Rotation",
            "baseName": "Rotation",
            "type": "number"
        },
        {
            "name": "Owner",
            "baseName": "Owner",
            "type": "number"
        },
        {
            "name": "LastAttack",
            "baseName": "LastAttack",
            "type": "number"
        },
        {
            "name": "ItemID",
            "baseName": "ItemID",
            "type": "number"
        },
        {
            "name": "Amount",
            "baseName": "Amount",
            "type": "number"
        },
        {
            "name": "Impact",
            "baseName": "Impact",
            "type": "number"
        },
        {
            "name": "OldOwner",
            "baseName": "OldOwner",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GangArea.attributeTypeMap;
    }
}

