/**
 * Vio-V
 * Vio-V API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GroupShop {
    'ShopId': number;
    'Money': number;
    'Mats': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ShopId",
            "baseName": "ShopId",
            "type": "number"
        },
        {
            "name": "Money",
            "baseName": "Money",
            "type": "number"
        },
        {
            "name": "Mats",
            "baseName": "Mats",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GroupShop.attributeTypeMap;
    }
}

