/**
 * Vio-V
 * Vio-V API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GroupFactory {
    'ID': number;
    'GroupID': number;
    'Storage': number;
    'NextCapture': number;
    'CraftingStorage'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ID",
            "baseName": "ID",
            "type": "number"
        },
        {
            "name": "GroupID",
            "baseName": "GroupID",
            "type": "number"
        },
        {
            "name": "Storage",
            "baseName": "Storage",
            "type": "number"
        },
        {
            "name": "NextCapture",
            "baseName": "NextCapture",
            "type": "number"
        },
        {
            "name": "CraftingStorage",
            "baseName": "CraftingStorage",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GroupFactory.attributeTypeMap;
    }
}

