/**
 * Vio-V
 * Vio-V API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GroupStorageLog {
    'GroupID': number;
    'Name': string;
    'Amount': string;
    'Item': string;
    'Timestamp': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "GroupID",
            "baseName": "GroupID",
            "type": "number"
        },
        {
            "name": "Name",
            "baseName": "Name",
            "type": "string"
        },
        {
            "name": "Amount",
            "baseName": "Amount",
            "type": "string"
        },
        {
            "name": "Item",
            "baseName": "Item",
            "type": "string"
        },
        {
            "name": "Timestamp",
            "baseName": "Timestamp",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GroupStorageLog.attributeTypeMap;
    }
}

