/**
 * Vio-V
 * Vio-V API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GroupMember {
    'CharacterID': number;
    'GroupID': number;
    'Rank': number;
    'Activity': number;
    'Name'?: string;
    'Permissions': string;
    'LastActivity': number;
    'Online'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "CharacterID",
            "baseName": "CharacterID",
            "type": "number"
        },
        {
            "name": "GroupID",
            "baseName": "GroupID",
            "type": "number"
        },
        {
            "name": "Rank",
            "baseName": "Rank",
            "type": "number"
        },
        {
            "name": "Activity",
            "baseName": "Activity",
            "type": "number"
        },
        {
            "name": "Name",
            "baseName": "Name",
            "type": "string"
        },
        {
            "name": "Permissions",
            "baseName": "Permissions",
            "type": "string"
        },
        {
            "name": "LastActivity",
            "baseName": "LastActivity",
            "type": "number"
        },
        {
            "name": "Online",
            "baseName": "Online",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return GroupMember.attributeTypeMap;
    }
}

