/**
 * Vio-V
 * Vio-V API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GroupOwnFactory {
    'ID'?: number;
    'Type': string;
    'GroupID': number;
    'MasterID': number;
    'Storage': string;
    'Settings': string;
    'CraftingStorages': string;
    'EXP': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ID",
            "baseName": "ID",
            "type": "number"
        },
        {
            "name": "Type",
            "baseName": "Type",
            "type": "string"
        },
        {
            "name": "GroupID",
            "baseName": "GroupID",
            "type": "number"
        },
        {
            "name": "MasterID",
            "baseName": "MasterID",
            "type": "number"
        },
        {
            "name": "Storage",
            "baseName": "Storage",
            "type": "string"
        },
        {
            "name": "Settings",
            "baseName": "Settings",
            "type": "string"
        },
        {
            "name": "CraftingStorages",
            "baseName": "CraftingStorages",
            "type": "string"
        },
        {
            "name": "EXP",
            "baseName": "EXP",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GroupOwnFactory.attributeTypeMap;
    }
}

