/**
 * Vio-V
 * Vio-V API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GroupRank {
    'RankID': number;
    'GroupID': number;
    'Name': string;
    'Bonus': number;
    'Leader': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "RankID",
            "baseName": "RankID",
            "type": "number"
        },
        {
            "name": "GroupID",
            "baseName": "GroupID",
            "type": "number"
        },
        {
            "name": "Name",
            "baseName": "Name",
            "type": "string"
        },
        {
            "name": "Bonus",
            "baseName": "Bonus",
            "type": "number"
        },
        {
            "name": "Leader",
            "baseName": "Leader",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return GroupRank.attributeTypeMap;
    }
}

