/**
 * Vio-V
 * Vio-V API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Storages {
    'ID'?: number;
    'Type': string;
    'Type_id': number;
    'MaxSize': number;
    'item_0': number;
    'item_1': number;
    'item_2': number;
    'item_3': number;
    'item_4': number;
    'item_5': number;
    'item_6': number;
    'item_7': number;
    'item_8': number;
    'item_9': number;
    'item_10': number;
    'item_11': number;
    'item_12': number;
    'item_13': number;
    'item_14': number;
    'item_15': number;
    'item_16': number;
    'item_17': number;
    'item_18': number;
    'item_19': number;
    'item_20': number;
    'item_21': number;
    'item_22': number;
    'item_23': number;
    'item_24': number;
    'item_25': number;
    'item_26': number;
    'item_27': number;
    'item_28': number;
    'item_29': number;
    'item_30': number;
    'item_31': number;
    'item_32': number;
    'item_33': number;
    'item_34': number;
    'item_35': number;
    'item_36': number;
    'item_37': number;
    'item_38': number;
    'item_39': number;
    'item_40': number;
    'item_41': number;
    'item_42': number;
    'item_43': number;
    'item_44': number;
    'item_45': number;
    'item_46': number;
    'item_47': number;
    'item_48': number;
    'item_49': number;
    'item_50': number;
    'item_51': number;
    'item_52': number;
    'item_53': number;
    'item_54': number;
    'item_55': number;
    'item_56': number;
    'item_57': number;
    'item_58': number;
    'item_59': number;
    'item_60': number;
    'item_61': number;
    'item_62': number;
    'item_63': number;
    'item_64': number;
    'item_65': number;
    'item_66': number;
    'item_67': number;
    'item_68': number;
    'item_69': number;
    'item_70': number;
    'item_71': number;
    'item_72': number;
    'item_73': number;
    'item_74': number;
    'item_75': number;
    'item_76': number;
    'item_77': number;
    'item_78': number;
    'item_79': number;
    'item_80': number;
    'item_81': number;
    'item_82': number;
    'item_83': number;
    'item_84': number;
    'item_85': number;
    'item_86': number;
    'item_87': number;
    'item_88': number;
    'item_89': number;
    'item_90': number;
    'item_91': number;
    'item_92': number;
    'item_93': number;
    'item_94': number;
    'item_95': number;
    'item_96': number;
    'item_97': number;
    'item_98': number;
    'item_99': number;
    'item_100': number;
    'item_101': number;
    'item_102': number;
    'item_103': number;
    'item_104': number;
    'item_105': number;
    'item_106': number;
    'item_107': number;
    'item_108': number;
    'item_109': number;
    'item_110': number;
    'item_111': number;
    'item_112': number;
    'item_113': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ID",
            "baseName": "ID",
            "type": "number"
        },
        {
            "name": "Type",
            "baseName": "Type",
            "type": "string"
        },
        {
            "name": "Type_id",
            "baseName": "Type_id",
            "type": "number"
        },
        {
            "name": "MaxSize",
            "baseName": "MaxSize",
            "type": "number"
        },
        {
            "name": "item_0",
            "baseName": "item_0",
            "type": "number"
        },
        {
            "name": "item_1",
            "baseName": "item_1",
            "type": "number"
        },
        {
            "name": "item_2",
            "baseName": "item_2",
            "type": "number"
        },
        {
            "name": "item_3",
            "baseName": "item_3",
            "type": "number"
        },
        {
            "name": "item_4",
            "baseName": "item_4",
            "type": "number"
        },
        {
            "name": "item_5",
            "baseName": "item_5",
            "type": "number"
        },
        {
            "name": "item_6",
            "baseName": "item_6",
            "type": "number"
        },
        {
            "name": "item_7",
            "baseName": "item_7",
            "type": "number"
        },
        {
            "name": "item_8",
            "baseName": "item_8",
            "type": "number"
        },
        {
            "name": "item_9",
            "baseName": "item_9",
            "type": "number"
        },
        {
            "name": "item_10",
            "baseName": "item_10",
            "type": "number"
        },
        {
            "name": "item_11",
            "baseName": "item_11",
            "type": "number"
        },
        {
            "name": "item_12",
            "baseName": "item_12",
            "type": "number"
        },
        {
            "name": "item_13",
            "baseName": "item_13",
            "type": "number"
        },
        {
            "name": "item_14",
            "baseName": "item_14",
            "type": "number"
        },
        {
            "name": "item_15",
            "baseName": "item_15",
            "type": "number"
        },
        {
            "name": "item_16",
            "baseName": "item_16",
            "type": "number"
        },
        {
            "name": "item_17",
            "baseName": "item_17",
            "type": "number"
        },
        {
            "name": "item_18",
            "baseName": "item_18",
            "type": "number"
        },
        {
            "name": "item_19",
            "baseName": "item_19",
            "type": "number"
        },
        {
            "name": "item_20",
            "baseName": "item_20",
            "type": "number"
        },
        {
            "name": "item_21",
            "baseName": "item_21",
            "type": "number"
        },
        {
            "name": "item_22",
            "baseName": "item_22",
            "type": "number"
        },
        {
            "name": "item_23",
            "baseName": "item_23",
            "type": "number"
        },
        {
            "name": "item_24",
            "baseName": "item_24",
            "type": "number"
        },
        {
            "name": "item_25",
            "baseName": "item_25",
            "type": "number"
        },
        {
            "name": "item_26",
            "baseName": "item_26",
            "type": "number"
        },
        {
            "name": "item_27",
            "baseName": "item_27",
            "type": "number"
        },
        {
            "name": "item_28",
            "baseName": "item_28",
            "type": "number"
        },
        {
            "name": "item_29",
            "baseName": "item_29",
            "type": "number"
        },
        {
            "name": "item_30",
            "baseName": "item_30",
            "type": "number"
        },
        {
            "name": "item_31",
            "baseName": "item_31",
            "type": "number"
        },
        {
            "name": "item_32",
            "baseName": "item_32",
            "type": "number"
        },
        {
            "name": "item_33",
            "baseName": "item_33",
            "type": "number"
        },
        {
            "name": "item_34",
            "baseName": "item_34",
            "type": "number"
        },
        {
            "name": "item_35",
            "baseName": "item_35",
            "type": "number"
        },
        {
            "name": "item_36",
            "baseName": "item_36",
            "type": "number"
        },
        {
            "name": "item_37",
            "baseName": "item_37",
            "type": "number"
        },
        {
            "name": "item_38",
            "baseName": "item_38",
            "type": "number"
        },
        {
            "name": "item_39",
            "baseName": "item_39",
            "type": "number"
        },
        {
            "name": "item_40",
            "baseName": "item_40",
            "type": "number"
        },
        {
            "name": "item_41",
            "baseName": "item_41",
            "type": "number"
        },
        {
            "name": "item_42",
            "baseName": "item_42",
            "type": "number"
        },
        {
            "name": "item_43",
            "baseName": "item_43",
            "type": "number"
        },
        {
            "name": "item_44",
            "baseName": "item_44",
            "type": "number"
        },
        {
            "name": "item_45",
            "baseName": "item_45",
            "type": "number"
        },
        {
            "name": "item_46",
            "baseName": "item_46",
            "type": "number"
        },
        {
            "name": "item_47",
            "baseName": "item_47",
            "type": "number"
        },
        {
            "name": "item_48",
            "baseName": "item_48",
            "type": "number"
        },
        {
            "name": "item_49",
            "baseName": "item_49",
            "type": "number"
        },
        {
            "name": "item_50",
            "baseName": "item_50",
            "type": "number"
        },
        {
            "name": "item_51",
            "baseName": "item_51",
            "type": "number"
        },
        {
            "name": "item_52",
            "baseName": "item_52",
            "type": "number"
        },
        {
            "name": "item_53",
            "baseName": "item_53",
            "type": "number"
        },
        {
            "name": "item_54",
            "baseName": "item_54",
            "type": "number"
        },
        {
            "name": "item_55",
            "baseName": "item_55",
            "type": "number"
        },
        {
            "name": "item_56",
            "baseName": "item_56",
            "type": "number"
        },
        {
            "name": "item_57",
            "baseName": "item_57",
            "type": "number"
        },
        {
            "name": "item_58",
            "baseName": "item_58",
            "type": "number"
        },
        {
            "name": "item_59",
            "baseName": "item_59",
            "type": "number"
        },
        {
            "name": "item_60",
            "baseName": "item_60",
            "type": "number"
        },
        {
            "name": "item_61",
            "baseName": "item_61",
            "type": "number"
        },
        {
            "name": "item_62",
            "baseName": "item_62",
            "type": "number"
        },
        {
            "name": "item_63",
            "baseName": "item_63",
            "type": "number"
        },
        {
            "name": "item_64",
            "baseName": "item_64",
            "type": "number"
        },
        {
            "name": "item_65",
            "baseName": "item_65",
            "type": "number"
        },
        {
            "name": "item_66",
            "baseName": "item_66",
            "type": "number"
        },
        {
            "name": "item_67",
            "baseName": "item_67",
            "type": "number"
        },
        {
            "name": "item_68",
            "baseName": "item_68",
            "type": "number"
        },
        {
            "name": "item_69",
            "baseName": "item_69",
            "type": "number"
        },
        {
            "name": "item_70",
            "baseName": "item_70",
            "type": "number"
        },
        {
            "name": "item_71",
            "baseName": "item_71",
            "type": "number"
        },
        {
            "name": "item_72",
            "baseName": "item_72",
            "type": "number"
        },
        {
            "name": "item_73",
            "baseName": "item_73",
            "type": "number"
        },
        {
            "name": "item_74",
            "baseName": "item_74",
            "type": "number"
        },
        {
            "name": "item_75",
            "baseName": "item_75",
            "type": "number"
        },
        {
            "name": "item_76",
            "baseName": "item_76",
            "type": "number"
        },
        {
            "name": "item_77",
            "baseName": "item_77",
            "type": "number"
        },
        {
            "name": "item_78",
            "baseName": "item_78",
            "type": "number"
        },
        {
            "name": "item_79",
            "baseName": "item_79",
            "type": "number"
        },
        {
            "name": "item_80",
            "baseName": "item_80",
            "type": "number"
        },
        {
            "name": "item_81",
            "baseName": "item_81",
            "type": "number"
        },
        {
            "name": "item_82",
            "baseName": "item_82",
            "type": "number"
        },
        {
            "name": "item_83",
            "baseName": "item_83",
            "type": "number"
        },
        {
            "name": "item_84",
            "baseName": "item_84",
            "type": "number"
        },
        {
            "name": "item_85",
            "baseName": "item_85",
            "type": "number"
        },
        {
            "name": "item_86",
            "baseName": "item_86",
            "type": "number"
        },
        {
            "name": "item_87",
            "baseName": "item_87",
            "type": "number"
        },
        {
            "name": "item_88",
            "baseName": "item_88",
            "type": "number"
        },
        {
            "name": "item_89",
            "baseName": "item_89",
            "type": "number"
        },
        {
            "name": "item_90",
            "baseName": "item_90",
            "type": "number"
        },
        {
            "name": "item_91",
            "baseName": "item_91",
            "type": "number"
        },
        {
            "name": "item_92",
            "baseName": "item_92",
            "type": "number"
        },
        {
            "name": "item_93",
            "baseName": "item_93",
            "type": "number"
        },
        {
            "name": "item_94",
            "baseName": "item_94",
            "type": "number"
        },
        {
            "name": "item_95",
            "baseName": "item_95",
            "type": "number"
        },
        {
            "name": "item_96",
            "baseName": "item_96",
            "type": "number"
        },
        {
            "name": "item_97",
            "baseName": "item_97",
            "type": "number"
        },
        {
            "name": "item_98",
            "baseName": "item_98",
            "type": "number"
        },
        {
            "name": "item_99",
            "baseName": "item_99",
            "type": "number"
        },
        {
            "name": "item_100",
            "baseName": "item_100",
            "type": "number"
        },
        {
            "name": "item_101",
            "baseName": "item_101",
            "type": "number"
        },
        {
            "name": "item_102",
            "baseName": "item_102",
            "type": "number"
        },
        {
            "name": "item_103",
            "baseName": "item_103",
            "type": "number"
        },
        {
            "name": "item_104",
            "baseName": "item_104",
            "type": "number"
        },
        {
            "name": "item_105",
            "baseName": "item_105",
            "type": "number"
        },
        {
            "name": "item_106",
            "baseName": "item_106",
            "type": "number"
        },
        {
            "name": "item_107",
            "baseName": "item_107",
            "type": "number"
        },
        {
            "name": "item_108",
            "baseName": "item_108",
            "type": "number"
        },
        {
            "name": "item_109",
            "baseName": "item_109",
            "type": "number"
        },
        {
            "name": "item_110",
            "baseName": "item_110",
            "type": "number"
        },
        {
            "name": "item_111",
            "baseName": "item_111",
            "type": "number"
        },
        {
            "name": "item_112",
            "baseName": "item_112",
            "type": "number"
        },
        {
            "name": "item_113",
            "baseName": "item_113",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Storages.attributeTypeMap;
    }
}

