/**
 * Vio-V
 * Vio-V API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SystemItem {
    'ID': number;
    'Name'?: string;
    'Description'?: string;
    'Weight'?: number;
    'Legal': number;
    'Heal': number;
    'Food': number;
    'PriceMin': number;
    'PriceMax': number;
    'AllowTrade': number;
    'Sync': number;
    'OnlyOnce': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ID",
            "baseName": "ID",
            "type": "number"
        },
        {
            "name": "Name",
            "baseName": "Name",
            "type": "string"
        },
        {
            "name": "Description",
            "baseName": "Description",
            "type": "string"
        },
        {
            "name": "Weight",
            "baseName": "Weight",
            "type": "number"
        },
        {
            "name": "Legal",
            "baseName": "Legal",
            "type": "number"
        },
        {
            "name": "Heal",
            "baseName": "Heal",
            "type": "number"
        },
        {
            "name": "Food",
            "baseName": "Food",
            "type": "number"
        },
        {
            "name": "PriceMin",
            "baseName": "PriceMin",
            "type": "number"
        },
        {
            "name": "PriceMax",
            "baseName": "PriceMax",
            "type": "number"
        },
        {
            "name": "AllowTrade",
            "baseName": "AllowTrade",
            "type": "number"
        },
        {
            "name": "Sync",
            "baseName": "Sync",
            "type": "number"
        },
        {
            "name": "OnlyOnce",
            "baseName": "OnlyOnce",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SystemItem.attributeTypeMap;
    }
}

