/**
 * Vio-V
 * Vio-V API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SystemGroupWar {
    'ID'?: string;
    'Deathmatch'?: string;
    'EndGameTimestamp'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "ID",
            "baseName": "ID",
            "type": "string"
        },
        {
            "name": "Deathmatch",
            "baseName": "Deathmatch",
            "type": "string"
        },
        {
            "name": "EndGameTimestamp",
            "baseName": "EndGameTimestamp",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SystemGroupWar.attributeTypeMap;
    }
}

